baseURL = "https://mindfultech.hk"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "zh_hk"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh_hk]
    languageCode = "zh_hk"
    languageName = "中文"
    weight = 1
    site_logo_text = "傳遞愛"
    title = "SMART ❤ 傳遞愛"
    contentDir = "content/zh_hk"
    [languages.zh_hk.params]
      description = "為 老年化社會 的 健康 和 福祉 而設的 綜合平台"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    site_logo_text = "for you"
    title = "SMART ❤ for you"
    contentDir = "content/en"
    [languages.en.params]
      description = "A platform for aging community's health & wellbeing."

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.png"
  description = "A platform for aging community's health & wellbeing."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  background_color_class = "bg-dark-green" # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  featured_image = "/images/hero_design.png"
  recent_posts_number = 2

  custom_css = ["css/custom.css"]
  cover_dimming_class = "bg-black-40"
  site_logo = "/images/logo.svg"

